# config/packages/nelmio_cors.yaml
nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['*'] # Autoriser toutes les origines (à adapter en production)
        allow_headers: ['*'] # Autoriser tous les en-têtes
        allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'] # Méthodes autorisées
        expose_headers: ['*']
        max_age: 3600
    paths:
        '^/api/': # Appliquer CORS uniquement aux routes commençant par /api/
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
            expose_headers: ['*']
            max_age: 3600